- name: reload apache
  systemd:
    name: apache2
    state: reloaded

- name: restart apache
  service: name=apache2 state=restarted

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: restart denyhosts
  service: name=denyhosts state=restarted

- name: restart monit
  service: name=monit state=restarted

- name: generate locales
  command: /usr/sbin/locale-gen

- name: detect sensors
  shell: /usr/sbin/sensors-detect < /dev/null

- include: munin-node.yml

- include: sysstat.yml

- name: restart systemd-hostnamed
  systemd:
    daemon_reload: yes
    name: systemd-hostnamed
    state: restarted
